name = "JuliaOulu2020"
uuid = "23f842cd-6296-44f9-9bb7-b17ff20d3bba"
authors = ["Carsten Bauer <crstnbr@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAdrv = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Traceur = "37b6cedf-1f77-55f8-9503-c64b63398394"
Unroll = "bec05c2e-cc06-5df2-90c3-340a513e71ff"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"
